services:
  rover-simulation:
    image: ros-gazebo
    container_name: ros-final
    user: ros
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
    volumes:
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/ros/.Xauthority 
    entrypoint: /home/ros/entrypoint_simulation.bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    network_mode: "host"
